# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 112b9568a6fec9877ef3b1c9294cfb64798bb265c239a213f8caead28fb542dc353e54e4be41cca3279986c1c3bb86fcc8a49967b008381f0801d1f43410c92f

test:
  secret_key_base: e557174475e5455dc0533bdf9f756ae22fe463597820db7bce053b5d1d6821594f047f24c45093a96b60117e982f7f5f7ef2bf9250fe25aeb006b0086294d0dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
